### PR TITLE
GUVNOR-2698: row descriptions included in conversion

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko Great job, thanks for the fix :-)

**Comment by jomarko** [comment]
@manstis I will look on fails in the evening. Please be patient.

**Comment by jomarko** [comment]
@manstis there were two problems:
* problem with multiple tables in one xls file 
* tables with more than 2 data rows

 Do you think can you have a look again? Sorry that my fix didn't come sooner.

**Comment by manstis** [comment]
@jomarko Looks good.. will wait for Jenkins to report a successful build before merging. Thanks!

**Pull request merged**
