### PR TITLE
[6.4.x] BZ1310208: When converting .XLS to GDT, Globals defined with short Class Names are converted to invalid Globals file

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1310208

This is the corollary of https://github.com/droolsjbpm/drools-wb/pull/130 for 6.4.x.

(cherry picked from commit 5e335d848d72f2d2fe1a4c84dcb89eb1a8742687)

### CODE REVIEW

**Comment by manstis** [comment]
I cloned my [fork](https://github.com/manstis/drools-wb) into a new folder, checked out ```BZ1310208-6.4.x``` branch and built locally with tests without problem. This is also *just* a cherry-pick of the ```master``` commit which builds [fine](https://github.com/droolsjbpm/drools-wb/pull/130).

**Comment by manstis** [comment]
Jenkins please retest.

**Comment by manstis** [comment]
@psiroky This is really strange.. tests pass locally for me with a fresh clone into an empty folder. The logs suggest tests are being ran in parallel. Could this be the cause on our CI slaves?

**Comment by psiroky** [comment]
@manstis yes, that could be the case. Those CI slaves are also considerably slower than average development machine. My guts are telling that disabling the SSH/Git daemons will fix this... (assuming they can be disabled for these tests).

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by Rikkola** [comment]
+1 once the tests pass.

**Comment by manstis** [comment]
**INVESTIGATING TEST FAILURES - PLEASE DO NOT MERGE**

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest.

**Comment by manstis** [comment]
Jenkins please retest.

**Comment by manstis** [comment]
@psiroky Please merge at your leisure!

**Pull request merged**
