### PR TITLE
[master] BZ 1271539 - fix the browser window title reset

### PR DESCRIPTION
**Pull request by zkrejcov**
This was probably left-over from some testing phase... The code might need more clean-up, but I don't see into it well enough.

### CODE REVIEW

**Comment by manstis** [comment]
The code you are removing does not need removing; it's the only feedback Users get on the progress of Guided Decision Table analysis - which,  for large tables, can take 10's of seconds.

**Comment by zkrejcov** [comment]
@manstis and it results in clearing the browser window title. Only for this one editor. Every time you open/focus a guided dt. 
I agree that it is good to give feedback, but... This is not a proper way to report such a thing. Besides the quite unique reporting style that is not used anywhere else in the gui, quite often there is only the beginning of the text displayed by the browser. If I expect some feedback from a webapp, I would rather expect it _inside_ the webapp, not "from the browser". Especially if everything else happens inside the webapp.
So, most times I'd guess, you now have the users do a double take - "what did I do...did I mess something up?" - because they will just see that the title gets cleared - for no obvious reason.

**Comment by manstis** [comment]
I agree with everything you've said; but your PR removes the (poor) feedback we give and replaces it with nothing. If you can replace with a status message in the Message Console (one entry that updates to show progress and then is removed) it'd be perfect :-)

**Comment by zkrejcov** [comment]
Looking into options..

**Comment by Rikkola** [comment]
Doing some changes on this area. Currently I print the info into the message console for testing, but the best I can think of would be in Analysis Reporting panel. A small bar on top or something like that.
Ticket for the issue. 
https://issues.jboss.org/browse/GUVNOR-2563

**Comment by manstis** [comment]
Assigned to @Rikkola .. please advise if this PR is still relevant; needs merging or closing etc.

**Comment by Rikkola** [comment]
Better to close. The ticket I made will replace this once fixed.

**Pull request closed without merging**
