### PR TITLE
GUVNOR-2503: Asset screen Validate-button should use incremental builder

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/GUVNOR-2503 and https://github.com/droolsjbpm/kie-wb-common/pull/421

### CODE REVIEW

**Comment by manstis** [comment]
@karreiro I hope to look in detail later..  but please delete the unused filter declarations; e.g. ```FILTER_JAVA``` etc from the classes you've modified.. it's pretty pointless keeping them.

**Comment by karreiro** [comment]
Thanks @manstis

**Comment by manstis** [comment]
+1 to merge (with other related PRs)

There are five PRs all together:-

- https://github.com/droolsjbpm/drools/pull/873
- https://github.com/droolsjbpm/guvnor/pull/346
- https://github.com/droolsjbpm/kie-wb-common/pull/421
- https://github.com/droolsjbpm/drools-wb/pull/265
- https://github.com/droolsjbpm/optaplanner-wb/pull/89

**Comment by Rikkola** [comment]
+1

**Pull request merged**
