### PR TITLE
GUVNOR-2290 - Move Find menu into Authoring perspective context menu

### PR DESCRIPTION
**Pull request by cristianonicolai**
Depends on https://github.com/uberfire/uberfire/pull/274

### CODE REVIEW

**Comment by manstis** [comment]
@cristianonicolai Is it possible to add the "Asset Search" menu item to ```drools-wb-webapp``` too? I use this webapp a lot during development and not having it mirror ```kie-drools-wb``` as closely as possible becomes a PITA (and I normally submit PRs to "add back" missing features)

**Comment by manstis** [comment]
Otherwise, +1 to merge.

**Comment by cristianonicolai** [comment]
@manstis unless I missed something, the update on AuthoringPerspective should had added it.

**Comment by manstis** [comment]
@cristianonicolai OK, I guess I was looking for the other "Find" item (see ```.newTopLevelCustomMenu( iocManager.lookupBean( SearchMenuBuilder.class ).getInstance() ).endMenu()``` in ```kie-wb-distributions```)?

**Comment by cristianonicolai** [comment]
oh, ok. done :)

**Comment by manstis** [comment]
@cristianonicolai Thanks

+1 to merge.

**Comment by csadilek** [comment]
master: baca96221bb864b6fad5985e9573bc2b141d2468

**Pull request closed without merging**
