### PR TITLE
[UF-448] Upgrade Templated Perspectives to Errai UI

### PR DESCRIPTION
**Pull request by ederign**
Depends on https://github.com/uberfire/uberfire/pull/581

### CODE REVIEW

**Comment by manstis** [comment]
@ederign The compilation failures look related to this PR

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by ederign** [comment]
@manstis which compilation failures?

**Comment by manstis** [comment]
@ederign the ones that were there before I asked Jenkins to rebuild it ;-)

**Pull request merged**
