### PR TITLE
Guided dtable V&V - ConditionInspectors unit tests

### PR DESCRIPTION
**Pull request by zkrejcov**
@Rikkola or @manstis or someone - could you please look at this bunch of tests?
Failing tests guaranteed. ;-)

### CODE REVIEW

**Comment by manstis** [comment]
Hi @zkrejcov This is (probably) going to have to wait for Toni.. we're battling the 6.3.0.Final (Community) release dead-line and looking into the (assured) failing tests is going to take some time. We can always cherry-pick back to 6.3.x for product if needed...

**Comment by triceo** [comment]
@manstis In the meantime, do you want BZs filed for these failures? That would have been the standard practice if we hadn't contributed tests instead.

**Comment by manstis** [comment]
@triceo I'd prefer a single BZ to be raised for (IDK) "Decision Table analysis issues" and reference this PR.. The BZ can be assigned to Toni. BTW this PR would probably need revision once I merge changes I've been making to improve performance (it'll be in 6.3.0.Final).

**Comment by zkrejcov** [comment]
@manstis no problem.

I'll work on that BZ next week.

**Comment by triceo** [comment]
@Rikkola While you were gone, this showed up. Bugs identified by this are being tracked here:
https://bugzilla.redhat.com/show_bug.cgi?id=1263233

**Comment by Rikkola** [comment]
Thanks for the BZ. I have most of the tests working already.

**Comment by triceo** [comment]
Awesome!

**Comment by Rikkola** [comment]
Made a new PR with the unit tests in this one.
https://github.com/droolsjbpm/drools-wb/pull/74

**Comment by zkrejcov** [comment]
Cool, thanks.

**Pull request closed without merging**
