### PR TITLE
GUVNOR-2478: XLS Conversion: project.imports file is created in wrong package

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2478

### CODE REVIEW

**Comment by manstis** [comment]
@Rikkola could you please review and +1.

**Comment by Rikkola** [comment]
+1

**Comment by csadilek** [comment]
@manstis @psiroky damn, merged, but clicked the wrong button so there's a merge commit now. let's deactivate traditional merges. wdyt?

**Comment by psiroky** [comment]
@csadilek yes, +1 for that. But it needs to be done for every repo separately, so quite a few clicks :)

**Comment by psiroky** [comment]
Configured for all repos (uf, dash, kie).

**Comment by csadilek** [comment]
@psiroky thanks!

**Pull request merged**
