### PR TITLE
GUVNOR-2557: Add keyboard navigation through the table

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2557

### CODE REVIEW

**Comment by manstis** [comment]
Needs https://github.com/uberfire/uberfire/pull/445

**Comment by triceo** [comment]
Thanks, @manstis ! @jhrcek will be happy to see this when he gets back from PTO. Do you need anyone from the team to take a look at this in the meantime?

**Comment by manstis** [comment]
@triceo No thank-you. I can walk @jhrcek through the editor when he returns.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@ederign Hi. Could you review this PR (it goes with https://github.com/uberfire/uberfire/pull/445 that you merged earlier). Thanks.

**Comment by mcimbora** [comment]
@manstis Code-wise this looks good to me.

**Pull request merged**
