### PR TITLE
GUVNOR-2580: Guided rule editor : Insert formulas in an OR/AND constraint

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2580

### CODE REVIEW

**Comment by manstis** [comment]
See https://github.com/droolsjbpm/drools/pull/823 too

**Comment by manstis** [comment]
This needs https://github.com/droolsjbpm/drools/pull/820 to replicate to Maven...

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
Tests are fine now. Some enforcer rules are failing though which are not related to this commit.

**Pull request merged**
