### PR TITLE
clean-up exception handling in DecisionTableXLSServiceImpl

### PR DESCRIPTION
**Pull request by zkrejcov**
- removed some duplicate logging (ExceptionUtilities.handleException(..) already logs the exception)
- added some stream closing
- added some more exception "handling" - let's be consistent when closing these streams

Hopefully, this doesn't create more mess. :)

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (when green).. The XLS ScoreCards backend is probably equally in need of some love.

**Comment by zkrejcov** [comment]
Again, failed compilation in jBPM :: KIE Services...

**Comment by mswiderski** [comment]
just noticed that and will work on fix for jBPM as it looks something has changed on kie ci level (MavenRepository.deployArtifact method)

**Comment by manstis** [comment]
@Salaboy @nmirasch Anyone looking into the failures in jBPM-console?

**Comment by manstis** [comment]
@mswiderski Speak to @mariofusco - he changed it earlier today.

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by zkrejcov** [comment]
And this time, we have compilation fail in Guvnor - Project Backend, RepositoryResolverTestUtils, again not related.

**Comment by zkrejcov** [comment]
jenkins retest this

**Comment by manstis** [comment]
+1 to merge.

**Pull request merged**
