### PR TITLE
Refactoring required by page Table extract

### PR DESCRIPTION
**Pull request by ederign**
https://github.com/uberfire/uberfire-extensions/pull/242

### CODE REVIEW

**Comment by ederign** [comment]
Child of https://github.com/uberfire/uberfire-extensions/pull/242

**Comment by manstis** [comment]
Does the ```gwt.xml``` file need to include an additional ```inherit``` too?

**Comment by manstis** [comment]
@ederign OK, thanks for clarifying gwt.xml question.

+1 to merge.

**Comment by csadilek** [comment]
master: e54fec664cf656382da53a8fbc5af4c1bb1a4efa

**Pull request closed without merging**
