### PR TITLE
GUVNOR-2630 : Verification & Validation: Condition and action changes are ignored

### PR DESCRIPTION
**Pull request by Rikkola**

### CODE REVIEW

**Comment by Rikkola** [comment]
@manstis @karreiro This is ready to be reviewed.

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
The ```RuleInspectorDumper``` is introduced here but not used (neither in app code nor tests)? Should it be?

**Comment by Rikkola** [comment]
It is used for debugging and bug hunting, comparing two strings is easier than using the super dev mode debug view for objects. It does feel stupid to keep it in production code. If anyone has a better place for it I can move it. I'm sure that I will also need it in the future.

**Comment by csadilek** [comment]
@Rikkola ok, got it. It's not a big deal as the type will be pruned in a production compile anyway, thanks to the GWT compiler. I just wasn't sure if that was its only purpose.

**Pull request merged**
