### PR TITLE
GUVNOR-2268 : Test Scenarios: Switch to using uberfire-extensions DatePicker

### PR DESCRIPTION
**Pull request by Rikkola**
Part uno. Can be merged in as it is. 
Part dos will remove the legacy date picker from kie-wb-commons and needs to be done after this. 

datepicker

### CODE REVIEW

**Comment by Rikkola** [comment]
Ok, found another location where the date picker is used. Please wait with the PR merge.

**Comment by Rikkola** [comment]
Ok, at first I only did the given section. Had to also do expect section.

**Comment by manstis** [comment]
*drools-wb*
(master) http://github.com/droolsjbpm/drools-wb/commit/c067b2379

**Comment by manstis** [comment]
Thanks @Rikkola !

**Pull request closed without merging**
