### PR TITLE
Bug 1304447 - [GSS](6.2.z) Not able to select specific branch from repository

### PR DESCRIPTION
**Pull request by Rikkola**
This is a side effect from removing the current branch from repository configuration. I change the magic map to  RepositoryEnvironmentConfigurations, just to make it more clear to use and make sure I changed all the locations.

https://github.com/droolsjbpm/guvnor/pull/264
https://github.com/droolsjbpm/kie-wb-common/pull/278
https://github.com/droolsjbpm/drools-wb/pull/132
https://github.com/droolsjbpm/jbpm-console-ng/pull/341
https://github.com/droolsjbpm/jbpm-designer/pull/161
https://github.com/droolsjbpm/jbpm-form-modeler/pull/38
https://github.com/droolsjbpm/optaplanner-wb/pull/38
https://github.com/droolsjbpm/kie-wb-distributions/pull/209

### CODE REVIEW

**Comment by manstis** [comment]
Seems OK (other than the compilation failure - moving to ```RepositoryEnvironmentConfigurations``` is going to bite all webapps - as you know)...

**Comment by Rikkola** [comment]
Yep doing the others now. Just threw guvnor+kie-wb-common out there for a review.

**Comment by manstis** [comment]
+1 to merge.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
master: 552c1d9a97aeb78b18e809fcc64afd0a53299ab1

**Pull request closed without merging**
