### PR TITLE
[6.5.x] GUVNOR-2585: In test scenario, expert contraint of type enum can be set but are always false

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/GUVNOR-2585

Auto-import enums from the class in order to avoid this:
enum-bug

### CODE REVIEW

**Comment by karreiro** [comment]
@manstis Could you review this? :-)

**Comment by manstis** [comment]
@Rikkola is king of Test Scenarios.. I'd prefer to defer review to him.

**Comment by manstis** [comment]
Requires https://github.com/droolsjbpm/drools/pull/935 too.

**Comment by Rikkola** [comment]
+1

**Pull request merged**
