### PR TITLE
[6.4.x] GUVNOR-2372: Guided Rule Editor: Copying/Renaming rules containing 'modify(x) {..' fails

### PR DESCRIPTION
**Pull request by manstis**
Corollary of https://github.com/droolsjbpm/drools-wb/pull/118
 
(cherry picked from commit 628d5b417a82852f3edfc0c1134982c91fea60b4)

### CODE REVIEW

**Comment by manstis** [comment]
This PR for 6.4.x includes the fix (to master) for https://github.com/droolsjbpm/drools-wb/pull/120

**Comment by csadilek** [comment]
@manstis build failure is not related with this change. @wmedvede can you take a look at this. it seems your recent refactoring causes issues on 6.4.x.

**Comment by manstis** [comment]
@csadilek yes, I just checked too :) The module (```drools-wb-guided-rule-editor```) compiles OK on 6.4.x  locally (and the changes were backend - so I don't expect any GWT issues).

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
6.4.x: c89d6a7ffa703bd6fca774aa9d0bf4fc68e499cc

**Pull request closed without merging**
