### PR TITLE
DROOLS-742 DecisionTableXLSToDecisionTableGuidedConverterTest fix.

### PR DESCRIPTION
**Pull request by baldimir**
See JIRA: https://issues.jboss.org/browse/DROOLS-742

### CODE REVIEW

**Comment by manstis** [comment]
Hello,

Could you please re-instate the test that checks the Model is correct after conversion? Whilst your changes for the "conditions" tests validate the data; they no longer validate the resulting Model classes. I think this is important.

Also, it'd be nice if you could use the code-style formatting we try to adhere to: https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/tree/master/ide-configuration.

Thanks,

Mike

**Comment by baldimir** [comment]
Hi, I made formatting changes. But it looks, that the formatter config which you linked is not actual. I use Idea 14 and i.e. the spaces after and before parenthesis are not there. 

Which test do you mean that I should reinstate? I didn't erase any test. I simply joined two tests that were the same . The only difference was in XLS file used and data rows that were checked at the end of the test. Everything that was tested there is still in the tests.

**Comment by manstis** [comment]
http://github.com/droolsjbpm/drools-wb/commit/dc97bf1bf

**Comment by manstis** [comment]
Sorry, my mistake. I looked at the code after your change and the test is fine.

Commits squashed and merged into master.

Thanks for the PR.

**Pull request closed without merging**
