### PR TITLE
[6.5.x] BPMSPL-301: request to improve error message while uploading spreadsheet with multibyte name

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/BPMSPL-301

This PR fixes the ConcurrentChangePopup (the "Uploading..." box was blocking the user from clicking in the popup buttons).

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Same comments as https://github.com/droolsjbpm/drools-wb/pull/240

**Comment by manstis** [comment]
+1 to merge.

**Comment by manstis** [comment]
Thanks @karreiro

**Pull request merged**
