### PR TITLE
[6.5.x] GUVNOR-2615: Editing dialog for 'Pattern' doesn't show selected value

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2615

Corollary of https://github.com/droolsjbpm/drools-wb/pull/246 for 6.5.x

(cherry picked from commit b53986a8310d55c52eb67c5fa335ca5980597acb)

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@Rikkola @karreiro Please could you review?

**Comment by Rikkola** [comment]
+1

**Pull request merged**
