### PR TITLE
GUVNOR-2544: Guided Decision Table Editor: Layout manager for tables.

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2544

### CODE REVIEW

**Comment by manstis** [comment]
Please also see https://github.com/uberfire/uberfire/pull/404

**Comment by csadilek** [comment]
jenkins retest this

**Comment by manstis** [comment]
@csadilek Probably needs https://github.com/droolsjbpm/drools-wb/pull/204 merging first.

**Comment by csadilek** [comment]
@manstis most failures seem to be caused by the wrong version of jgit / ip bom upgrade we did earlier today.

**Comment by csadilek** [comment]
@manstis I tested drools-wb after the upgrade so something was stale during the last build on jenkins.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
@manstis build works fine locally.

**Comment by csadilek** [comment]
+1

**Comment by manstis** [comment]
Thanks @csadilek I was going to [send the boys round](http://www.urbandictionary.com/define.php?term=send%20the%20boys%20round) to see Jenkins sooner than later ;-)

**Pull request merged**
