### PR TITLE
[6.3.x] Bug 1316566 - User can not create projects in any other repository than master

### PR DESCRIPTION
**Pull request by Rikkola**
Ticket for this branch is here: https://bugzilla.redhat.com/show_bug.cgi?id=1316566

(cherry picked from commit 73f2caabef25bd466502ef5eb698053fb0a2dcdf)

https://github.com/droolsjbpm/guvnor/pull/286
https://github.com/droolsjbpm/kie-wb-common/pull/310
https://github.com/droolsjbpm/drools-wb/pull/144
https://github.com/droolsjbpm/jbpm-console-ng/pull/365
https://github.com/droolsjbpm/kie-wb-distributions/pull/229

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (I suspect the CI failure relates to differences in branch names?)

**Comment by Rikkola** [comment]
Nope, it actually did find something. I admit I'm running the build on Jenkins before making the PRs, trying to save some time.

**Comment by Rikkola** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
+1 to merge.. @csadilek all yours!

**Pull request merged**
