### PR TITLE
[RHBRMS-2675] pdfbox: XML External Entity vulnerability

### PR DESCRIPTION
**Pull request by mbiarnes**
makes only sense to merge when new jboss-ip-bom 7.0.0.CR6 was released

### CODE REVIEW

**Comment by manstis** [comment]
@mbiarnes The build failure looks directly related to your change :-(

**Comment by mbiarnes** [comment]
@manstis this will only work if the upcoming jboss-ip-bom 7.0.0.CR6 was released and the droolsjbpm-build-bootstrap/pom.xml was upgraded to use it, as the deoendency to org.apache.pdfbox is defined in the jboss-ip-bpm.

**Comment by manstis** [comment]
@mbiarnes OK, so I guess we can only approve and merge this when jboss-ip-bom 7.0.0.CR6 is released.

**Comment by mbiarnes** [comment]
@manstis correct

**Comment by psiroky** [comment]
jenkins retest this

**Comment by manstis** [comment]
@psiroky @mbiarnes Is this PR good to go yet?

**Pull request merged**
