### PR TITLE
RHBPMS-856: GDT header for merged condition columns

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
Please do not merge yet.

**Comment by manstis** [comment]
@jomarko Looks good to me - just need a test for RHBPMS-856 (```BRLColumn``` column headings)

**Comment by jomarko** [comment]
@manstis thanks. Please stay tuned. I am working on it.

**Comment by manstis** [comment]
@jomarko Hi.. what's the status please? @etirelli is asking for inclusion in the upcoming release.

**Comment by manstis** [comment]
@jomarko has confirmed that more unit tests are pending.

Otherwise the PR is good to go.

**Comment by manstis** [comment]
Merged "as is" as sanctioned by @etirelli

**Pull request merged**
