### PR TITLE
fixes SDM for some people

### PR DESCRIPTION
**Pull request by Rikkola**

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@Rikkola @ederign It definitely makes a difference for me (and besides, why should ```drools-wb-verifier-core``` be ```provided``` when ```drools-wb-verifier-client``` is not?). Unless somebody can give a compelling reason not to merge I will do so (on Monday).

**Comment by psiroky** [comment]
+1 to remove the `<provided>` scope if this is direct dependency.

**Comment by csadilek** [comment]
+1, I know, I know I am picky, but @Rikkola could you please change the commit message to i.e. "Set drools-wb-verifier-core dep. to compile scope to fix SDM." It's much more descriptive than "fix SDM for some people'" :)

**Comment by Rikkola** [comment]
Done. Jenkins please retest. Rebased the branch.

**Pull request merged**
