### PR TITLE
[UF-403] Fork and Mirror

### PR DESCRIPTION
**Pull request by adrielparedes**
The goal is to have the possibility to fork any git repository inside the niogit directory.
To complete the goal we need:

* Separate git repositories into different directories. Those directories are named like the Organizational Units.
* Create a Fork command that copy all the content of the repository to fork and add the reference to the internal path of the origin repository.
* Write information about fork so we can track where those forks are, how many forks has those repositories, etc.

### CODE REVIEW

**Comment by manstis** [comment]
ok to test

**Comment by manstis** [comment]
The [PR](https://github.com/droolsjbpm/guvnor/pull/361) (in guvnor) has lead to failure of many tests in ```drools-wb``` (and consequentially I also expect in other modules that have tests for indexing).

**Comment by adrielparedes** [comment]
@manstis where can I find BaseIndexingTest? I need to change something there about internal git path (all this because of a uberfire change)

**Comment by manstis** [comment]
@adrielparedes Hello, you can find it [here](https://github.com/droolsjbpm/kie-wb-common/blob/master/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/test/java/org/kie/workbench/common/services/refactoring/backend/server/BaseIndexingTest.java).

**Comment by adrielparedes** [comment]
@manstis I'm not adding the ForkPresenter/View so I'm going to close this PR because is not necessary anymore. Are you ok with that?

**Comment by manstis** [comment]
@adrielparedes I am OK with closing this PR.

**Pull request closed without merging**
