### PR TITLE
add message to thrown exception

### PR DESCRIPTION
**Pull request by zkrejcov**

### CODE REVIEW

**Comment by zkrejcov** [comment]
Check fails due to compilation failure somewhere in jbpm - I do believe this is not related...

**Comment by manstis** [comment]
+1 to merge.

**Comment by manstis** [comment]
@zkrejcov Thanks.

**Comment by manstis** [comment]
@zkrejcov Looks like you need to adapt your change here (and any other PRs) :(

.. and I need to refresh my knowledge of what JDK classes/methods are emulated by GWT.

**Comment by manstis** [comment]
..and I must *not* merge PRs until they're green (it is all too easy to think "ah.. simple change.., I see build error is not related/downstream...merge.."

**Comment by zkrejcov** [comment]
No problem, will send a new PR asap. I think this was the only place where I used it...

**Comment by zkrejcov** [comment]
https://github.com/droolsjbpm/drools-wb/pull/164

**Pull request merged**
