### PR TITLE
GUVNOR-2585: In test scenario, expert contraint of type enum can be set but are always false

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/GUVNOR-2585

Auto-import enums from the class in order to avoid this:
enum-bug

### CODE REVIEW

**Comment by karreiro** [comment]
@manstis Could you review this? :-)

**Comment by manstis** [comment]
@Rikkola is king of Test Scenarios.. I'd prefer to defer review to him.

**Comment by jhrcek** [comment]
@karreiro just out of curiosity: what tool did you use to "record" the gif?

**Comment by karreiro** [comment]
@jhrcek I'm using this one: https://github.com/GNOME/byzanz ;-)

**Pull request merged**
