### PR TITLE
[6.5.x] RHBPMS-4275: Guided Decision Table: XLS can not be validated

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/RHBPMS-4275

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:

- https://github.com/droolsjbpm/guvnor/pull/365
- https://github.com/droolsjbpm/kie-wb-common/pull/476
- https://github.com/droolsjbpm/drools-wb/pull/298

**Comment by manstis** [comment]
@romartin Failure is due to https://github.com/uberfire/uberfire/pull/509#issuecomment-248337416

Looking into including a fix with this PR.

**Comment by karreiro** [comment]
+1

**Comment by karreiro** [comment]
+1

**Pull request merged**
