### PR TITLE
GUVNOR-2866: [Guided Decision Table] Columns swaping doesn't work in all cases

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2866

There actually wasn't any support for DnD'ing "BRL" columns.

### CODE REVIEW

**Comment by manstis** [comment]
@Rikkola @karreiro Would you mind reviewing please, when you get a chance?

**Comment by karreiro** [comment]
@manstis I think that there are some formatting issues.

**Comment by manstis** [comment]
@karreiro Unfortunately there are no formatting issues; there is a new "code style formatter" in ```droolsjbpm-build-bootstrap``` specifically you could read [this](https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/358) and the referenced PRs.. I did ask for it to be communicated to BSIG, but it looks like it never happened :-(

**Comment by karreiro** [comment]
@manstis thanks! :-)

**Pull request merged**
