### PR TITLE
BPMSPL-252: [GSS-RFE] Ability to check duplicate of ReleaseId (GroupId, ArtifactId and Version) with existing projects

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/BPMSPL-252

### CODE REVIEW

**Comment by manstis** [comment]
Part of the following ensemble:

https://github.com/droolsjbpm/drools/pull/633
https://github.com/droolsjbpm/guvnor/pull/240
https://github.com/droolsjbpm/kie-wb-common/pull/236
https://github.com/droolsjbpm/drools-wb/pull/117
https://github.com/droolsjbpm/kie-wb-distributions/pull/187

**Comment by manstis** [comment]
@Rikkola Would you mind taking a look please?

**Comment by manstis** [comment]
*Documentation*
https://github.com/droolsjbpm/kie-docs/pull/40

**Comment by Rikkola** [comment]
+1

**Comment by csadilek** [comment]
master: b3688336769b6ffd7e00e4ad8e0374a38e3f0c3d

**Pull request closed without merging**
