### PR TITLE
Removing redundancy.

### PR DESCRIPTION
**Pull request by Rikkola**
@manstis 
@paulovmr 
I noticed we have the class for docks in kie-wb-common. Is it ok to remove this one?

### CODE REVIEW

**Comment by paulovmr** [comment]
@Rikkola It's ok by me, if it is still working after the change :). I'll let @manstis take a look and give his +1 to be sure.

**Comment by manstis** [comment]
@Rikkola Did you try running ```drools-wb-webapp``` with the class deleted? (And checked Data Modeller still has the docks for annotations - "drools", "JPA" and "Advanced"?)

**Comment by manstis** [comment]
@wmedvede Hi... can you verify removing "Authoring Dock" from ```drools-wb-webapp``` is OK?

**Comment by manstis** [comment]
@Rikkola advised he'd ran ```drools-wb-webapp``` and (Data Modeller) Docks were OK.

+1 to merge.

**Pull request merged**
